POST https://sinarmas-digital-day.glitch.me/vvip
Content-Type: application/json
Authorization: Basic U2luYXJtYXNEaWdpdGFsRGF5OkM0VnJIbFh0UlR6VHp0aGZjZlVaMm5vWTRRcm5RVw==

{ 
    "name":"Muhammad Arif Rofiudin 2",
    "is_vvip":true,
    "position":"Chairman of PT Sinar Mas Agro Resources & Technology Tbk"
}

###

POST https://sinarmas-digital-day.glitch.me/non-vvip
Content-Type: application/json
Authorization: Basic U2luYXJtYXNEaWdpdGFsR

{ 
    "name":"Elizabeth Jayne",
    "is_vvip":false
}

###

POST http://imajiwa.cloud/vvip
Content-Type: application/json
Authorization: Basic U2luYXJtYXNEaWdpdGFsRGF5OkM0VnJIbFh0UlR6VHp0aGZjZlVaMm5vWTRRcm5RVw==

{ 
    "name":"Muhammad Arif hermanto",
    "is_vvip":true,
    "position":"Chairman of PT Sinar Mas Agro Resources & Technology Tbk"
}

###

POST http://imajiwa.cloud/non-vvip
Content-Type: application/json
Authorization: Basic U2luYXJtYXNEaWdpdGFsRGF5OkM0VnJIbFh0UlR6VHp0aGZjZlVaMm5vWTRRcm5RVw==

{ 
    "name":"NON VVIP 4kk",
    "is_vvip":false
}